namespace: ms-order

secrets:
  reload: False
  dbuser: msorder-db-user
  dbpass: msorder-db-pass
  dbhost: postgres-service
  dbport: 5432
  dbname: order
  db_max_connections: 10
  dc_pool_recycle: 60

api:
  replicas: 1
  image: 
    repository: nikfedoseev/microservice-architecture-homeworks
    tag: homework7
  imagePullPolicy: Always
  port: 8000
  containerEnv:
    RELOAD: reload
    DB_USER: dbuser
    DB_PASS: dbpass
    DB_HOST: dbhost
    DB_PORT: dbport
    DB_NAME: dbname
    DB_MAX_CONNECTIONS: db_max_connections
    DC_POOL_RECYCLE: dc_pool_recycle
  migrationEnv:
    DB_USER: dbuser
    DB_PASS: dbpass
    DB_HOST: dbhost
    DB_PORT: dbport
    DB_NAME: dbname

service:
  ports:
    - name: api
      port: 9000
      targetPort: 8000

postgres:
  namespace: ms-order
  env:
    POSTGRES_USER: msorder-db-user
    POSTGRES_PASSWORD: msorder-db-pass
    POSTGRES_DB: order
  port: 5432