{
 "title": "MyDashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler!=\"/api/healthcheck\", status=~\"5.+\"}) / \nsum(http_requests_total{handler!=\"/api/healthcheck\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Controller Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_requests{status=~\"5.+\"}) / \nsum(nginx_ingress_controller_requests{}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, handler, method) (rate(http_request_duration_seconds_bucket{handler!=\"/api/healthcheck\"}[1m])))",
     "legendFormat": "{handler=\"{{handler}}\", method=\"{{method}}\" q=0.5}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, handler, method) (rate(http_request_duration_seconds_bucket{handler!=\"/api/healthcheck\"}[1m])))",
     "legendFormat": "{handler=\"{{handler}}\", method=\"{{method}}\" q=0.95}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, handler, method) (rate(http_request_duration_seconds_bucket{handler!=\"/api/healthcheck\"}[1m])))",
     "legendFormat": "{handler=\"{{handler}}\", method=\"{{method}}\" q=0.99}"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, handler, method) (rate(http_request_duration_seconds_bucket{handler!=\"/api/healthcheck\"}[1m])))",
     "legendFormat": "{handler=\"{{handler}}\", method=\"{{method}}\" q=max}"
    }
   ]
  },
  {
   "title": "Ingress Controller Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by api endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!~\"/api/healthcheck\"}[1m])) by (handler, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Controller RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}